### ISSUE TITLE
Custom element doesn’t exist: gui-sandbox 

### ISSUE THREAD

**Issue by johntdyer** [thomasloven/lovelace-gui-sandbox#2]
HASS 0.100.2
YAML Mode: true

I created a separate tab in Lovelace with a single entity 

```yaml
type: custom:gui-sandbox
```

And I added the module in the resources list and even restarted but I am still getting this error.  I installed via HAC’s and have also tried reinstalling it via HACS to see if that maybe would help...

**Comment by thomasloven** [comment]
Did you "[see this guide](https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins)"?

**Comment by johntdyer** [comment]
I sorted this out, I was using the wrong path for the js... sorry
